In [24]:
import pandas as pd

In [25]:
df = pd.read_parquet('../data/Dados_commodities_mensal_nova.parquet')

In [26]:
df

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
0,PRECO,2024,12,COMMODITIES_CO_GRUPO_4,"119,99877083983135",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
1,PRECO,2024,12,COMMODITIES_CO_GRUPO_2,"141,50202769961788",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
2,PRECO,2024,12,COMMODITIES_CO_GRUPO_3,"186,03067015795551",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
3,PRECO,2024,12,COMMODITIES_CO_GRUPO_1,"180,29747355381787",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
4,PRECO,2024,12,COMMODITIES_TOTAL_1,"160,28639354962223",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9643,PRECO,1998,1,COMMODITIES_TOTAL_1,"42,64480995344425",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
9644,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_2,"155,14675915346666",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9645,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_3,"58,37790758508214",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9646,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_1,"145,25564575150008",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9647,QUANTUM,1998,1,COMMODITIES_TOTAL_1,"115,89236396419047",IMP,USD,Total Commodities,COMMODITIES,Total Commodities

### Separando os dataframes pelo tipo do índice (PREÇO ou QUANTUM)

In [27]:
def get_series_by_tipo_indice(df):
    df_preco = df[df['TIPO_INDICE'] == 'PRECO']
    df_quantum = df[df['TIPO_INDICE'] == 'QUANTUM']

    return df_preco, df_quantum

In [28]:
df_preco, df_quantum = get_series_by_tipo_indice(df)

In [29]:
df_preco

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
0,PRECO,2024,12,COMMODITIES_CO_GRUPO_4,"119,99877083983135",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
1,PRECO,2024,12,COMMODITIES_CO_GRUPO_2,"141,50202769961788",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
2,PRECO,2024,12,COMMODITIES_CO_GRUPO_3,"186,03067015795551",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
3,PRECO,2024,12,COMMODITIES_CO_GRUPO_1,"180,29747355381787",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
4,PRECO,2024,12,COMMODITIES_TOTAL_1,"160,28639354962223",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9635,PRECO,1998,1,COMMODITIES_TOTAL_1,"94,28163288367739",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9640,PRECO,1998,1,COMMODITIES_CO_GRUPO_2,"82,90929209676982",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9641,PRECO,1998,1,COMMODITIES_CO_GRUPO_3,"50,95613009936341",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9642,PRECO,1998,1,COMMODITIES_CO_GRUPO_1,"100,17938813467910",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9643,PRECO,1998,1,COMMODITIES_TOTAL_1,"42,64480995344425",IMP,USD,Total Commodities,COMMODITIES,Total Commodities

In [30]:
df_quantum

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
5,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_4,"170,86239667298014",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
6,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_2,"228,17373917510147",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
7,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_3,"150,99963004432325",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
8,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_1,"179,46849171269511",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9,QUANTUM,2024,12,COMMODITIES_TOTAL_1,"173,18432351798012",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9639,QUANTUM,1998,1,COMMODITIES_TOTAL_1,"32,07088610388959",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9644,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_2,"155,14675915346666",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9645,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_3,"58,37790758508214",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9646,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_1,"145,25564575150008",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9647,QUANTUM,1998,1,COMMODITIES_TOTAL_1,"115,89236396419047",IMP,USD,Total Commodities,COMMODITIES,Total Commodities

### Separando os dataframes pelo tipo (CORRENTE, EXP ou IMP)

In [31]:
def get_series_by_tipo(df):
    df_corr = df[df['TIPO'] == 'CORRENTE']
    df_exp = df[df['TIPO'] == 'EXP']
    df_imp = df[df['TIPO'] == 'IMP']

    return df_corr, df_exp, df_imp

#### Preço

In [32]:
df_preco_corr, df_preco_exp, df_preco_imp = get_series_by_tipo(df_preco)

In [33]:
df_preco_corr

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
0,PRECO,2024,12,COMMODITIES_CO_GRUPO_4,"119,99877083983135",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
1,PRECO,2024,12,COMMODITIES_CO_GRUPO_2,"141,50202769961788",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
2,PRECO,2024,12,COMMODITIES_CO_GRUPO_3,"186,03067015795551",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
3,PRECO,2024,12,COMMODITIES_CO_GRUPO_1,"180,29747355381787",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
4,PRECO,2024,12,COMMODITIES_TOTAL_1,"160,28639354962223",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9603,PRECO,1998,2,COMMODITIES_TOTAL_1,"70,81237111129171",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
9624,PRECO,1998,1,COMMODITIES_CO_GRUPO_2,"102,74151657217227",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9625,PRECO,1998,1,COMMODITIES_CO_GRUPO_3,"56,84606482647145",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9626,PRECO,1998,1,COMMODITIES_CO_GRUPO_1,"112,97962509293602",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9627,PRECO,1998,1,COMMODITIES_TOTAL_1,"72,52618931305419",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities

In [34]:
df_preco_exp

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
10,PRECO,2024,12,COMMODITIES_CO_GRUPO_4,"124,66928093606960",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
11,PRECO,2024,12,COMMODITIES_CO_GRUPO_2,"144,19977605555368",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
12,PRECO,2024,12,COMMODITIES_CO_GRUPO_3,"194,31993414767933",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
13,PRECO,2024,12,COMMODITIES_CO_GRUPO_1,"180,08146229603679",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
14,PRECO,2024,12,COMMODITIES_TOTAL_1,"169,29384912605829",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9611,PRECO,1998,2,COMMODITIES_TOTAL_1,"90,63914192819091",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9632,PRECO,1998,1,COMMODITIES_CO_GRUPO_2,"104,37003188387564",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9633,PRECO,1998,1,COMMODITIES_CO_GRUPO_3,"57,96917184835647",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9634,PRECO,1998,1,COMMODITIES_CO_GRUPO_1,"126,08896425079254",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9635,PRECO,1998,1,COMMODITIES_TOTAL_1,"94,28163288367739",EXP,USD,Total Commodities,COMMODITIES,Total Commodities

In [35]:
df_preco_imp

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
20,PRECO,2024,12,COMMODITIES_CO_GRUPO_4,"125,13048085029550",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
21,PRECO,2024,12,COMMODITIES_CO_GRUPO_2,"124,87354338785053",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
22,PRECO,2024,12,COMMODITIES_CO_GRUPO_3,"142,11327685811079",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
23,PRECO,2024,12,COMMODITIES_CO_GRUPO_1,"192,83755319057852",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
24,PRECO,2024,12,COMMODITIES_TOTAL_1,"138,47335890271017",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9619,PRECO,1998,2,COMMODITIES_TOTAL_1,"40,87159989848013",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
9640,PRECO,1998,1,COMMODITIES_CO_GRUPO_2,"82,90929209676982",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9641,PRECO,1998,1,COMMODITIES_CO_GRUPO_3,"50,95613009936341",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9642,PRECO,1998,1,COMMODITIES_CO_GRUPO_1,"100,17938813467910",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9643,PRECO,1998,1,COMMODITIES_TOTAL_1,"42,64480995344425",IMP,USD,Total Commodities,COMMODITIES,Total Commodities

#### Quantum

In [36]:
df_quantum_corr, df_quantum_exp, df_quantum_imp = get_series_by_tipo(df_quantum)

In [37]:
df_quantum_corr

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
5,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_4,"170,86239667298014",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
6,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_2,"228,17373917510147",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
7,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_3,"150,99963004432325",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
8,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_1,"179,46849171269511",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9,QUANTUM,2024,12,COMMODITIES_TOTAL_1,"173,18432351798012",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9607,QUANTUM,1998,2,COMMODITIES_TOTAL_1,"40,78726372101026",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
9628,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_2,"46,32429504749362",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9629,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_3,"65,35161591839740",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9630,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_1,"37,05754266327946",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9631,QUANTUM,1998,1,COMMODITIES_TOTAL_1,"48,12596859693230",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities

In [38]:
df_quantum_exp

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
15,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_4,"245,84601038438771",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
16,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_2,"242,43654780639378",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
17,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_3,"147,81907804930862",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
18,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_1,"179,46774036931902",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
19,QUANTUM,2024,12,COMMODITIES_TOTAL_1,"185,82852062827286",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9615,QUANTUM,1998,2,COMMODITIES_TOTAL_1,"26,86282493448991",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9636,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_2,"36,70130627941437",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9637,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_3,"73,94792465389726",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9638,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_1,"25,10838396845480",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9639,QUANTUM,1998,1,COMMODITIES_TOTAL_1,"32,07088610388959",EXP,USD,Total Commodities,COMMODITIES,Total Commodities

In [39]:
df_quantum_imp

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
25,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_4,"107,35747872105688",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
26,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_2,"58,62590884552954",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
27,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_3,"189,05246277566673",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
28,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_1,"162,93325353356767",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
29,QUANTUM,2024,12,COMMODITIES_TOTAL_1,"135,27295313305990",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9623,QUANTUM,1998,2,COMMODITIES_TOTAL_1,"104,10339838071651",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
9644,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_2,"155,14675915346666",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9645,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_3,"58,37790758508214",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9646,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_1,"145,25564575150008",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9647,QUANTUM,1998,1,COMMODITIES_TOTAL_1,"115,89236396419047",IMP,USD,Total Commodities,COMMODITIES,Total Commodities

### Separando os dataframes pelo tipo de commodities (Combustíveis, Matérias-Primas Agrícolas, Minerais, Minérios E Metais, Todos Alimentos, Total Commodities)

In [40]:
def get_series_by_tipo(df):
    df_comb = df[df['NO_COMMODITIES'] == 'Combustíveis']
    df_mpa = df[df['NO_COMMODITIES'] == 'Matérias-Primas Agrícolas']
    df_mmm = df[df['NO_COMMODITIES'] == 'Minerais, Minérios E Metais']
    df_ta = df[df['NO_COMMODITIES'] == 'Todos Alimentos']
    df_tc = df[df['NO_COMMODITIES'] == 'Total Commodities']

    return df_comb, df_mpa, df_mmm, df_ta, df_tc

#### Preco - Corrente

In [41]:
df_preco_corr_comb, df_preco_corr_mpa, df_preco_corr_mmm, df_preco_corr_ta, df_preco_corr_tc = get_series_by_tipo(df_preco_corr)

In [44]:
df_preco_corr_comb

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
0,PRECO,2024,12,COMMODITIES_CO_GRUPO_4,"119,99877083983135",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
30,PRECO,2024,11,COMMODITIES_CO_GRUPO_4,"133,52570986498426",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
60,PRECO,2024,10,COMMODITIES_CO_GRUPO_4,"129,84581433454954",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
90,PRECO,2024,9,COMMODITIES_CO_GRUPO_4,"137,57199238871615",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
120,PRECO,2024,8,COMMODITIES_CO_GRUPO_4,"138,31898759550685",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
...,...,...,...,...,...,...,...,...,...,...
9210,PRECO,1999,5,COMMODITIES_CO_GRUPO_4,"27,42155347876015",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
9240,PRECO,1999,4,COMMODITIES_CO_GRUPO_4,"23,82308151652498",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
9270,PRECO,1999,3,COMMODITIES_CO_GRUPO_4,"21,88942296208537",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
9300,PRECO,1999,2,COMMODITIES_CO_GRUPO_4,"21,99050334161312",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
9330,PRECO,1999,1,COMMODITIES_CO_GRUPO_4,"20,57268087089938",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis

In [45]:
df_preco_corr_mpa

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
1,PRECO,2024,12,COMMODITIES_CO_GRUPO_2,"141,50202769961788",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
31,PRECO,2024,11,COMMODITIES_CO_GRUPO_2,"140,87845388579473",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
61,PRECO,2024,10,COMMODITIES_CO_GRUPO_2,"143,44489097505857",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
91,PRECO,2024,9,COMMODITIES_CO_GRUPO_2,"152,99596673785356",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
121,PRECO,2024,8,COMMODITIES_CO_GRUPO_2,"153,56048268459440",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
...,...,...,...,...,...,...,...,...,...,...
9528,PRECO,1998,5,COMMODITIES_CO_GRUPO_2,"99,69906536195285",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9552,PRECO,1998,4,COMMODITIES_CO_GRUPO_2,"97,24091156552220",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9576,PRECO,1998,3,COMMODITIES_CO_GRUPO_2,"96,19072703929173",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9600,PRECO,1998,2,COMMODITIES_CO_GRUPO_2,"100,26924498253416",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9624,PRECO,1998,1,COMMODITIES_CO_GRUPO_2,"102,74151657217227",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas

In [46]:
df_preco_corr_mmm

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
2,PRECO,2024,12,COMMODITIES_CO_GRUPO_3,"186,03067015795551",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
32,PRECO,2024,11,COMMODITIES_CO_GRUPO_3,"183,80799363240072",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
62,PRECO,2024,10,COMMODITIES_CO_GRUPO_3,"175,16529023969812",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
92,PRECO,2024,9,COMMODITIES_CO_GRUPO_3,"177,63513777418481",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
122,PRECO,2024,8,COMMODITIES_CO_GRUPO_3,"180,80853190795801",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
...,...,...,...,...,...,...,...,...,...,...
9529,PRECO,1998,5,COMMODITIES_CO_GRUPO_3,"55,90693996569943",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9553,PRECO,1998,4,COMMODITIES_CO_GRUPO_3,"56,49106537371138",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9577,PRECO,1998,3,COMMODITIES_CO_GRUPO_3,"56,64374316937820",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9601,PRECO,1998,2,COMMODITIES_CO_GRUPO_3,"55,99160967613562",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9625,PRECO,1998,1,COMMODITIES_CO_GRUPO_3,"56,84606482647145",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"

In [47]:
df_preco_corr_ta

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
3,PRECO,2024,12,COMMODITIES_CO_GRUPO_1,"180,29747355381787",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
33,PRECO,2024,11,COMMODITIES_CO_GRUPO_1,"180,26869915655615",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
63,PRECO,2024,10,COMMODITIES_CO_GRUPO_1,"177,36315752291890",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
93,PRECO,2024,9,COMMODITIES_CO_GRUPO_1,"173,66373132567782",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
123,PRECO,2024,8,COMMODITIES_CO_GRUPO_1,"173,26887517736063",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
...,...,...,...,...,...,...,...,...,...,...
9530,PRECO,1998,5,COMMODITIES_CO_GRUPO_1,"98,81845512653334",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9554,PRECO,1998,4,COMMODITIES_CO_GRUPO_1,"103,38165923554661",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9578,PRECO,1998,3,COMMODITIES_CO_GRUPO_1,"109,07594246187546",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9602,PRECO,1998,2,COMMODITIES_CO_GRUPO_1,"112,00901038334715",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9626,PRECO,1998,1,COMMODITIES_CO_GRUPO_1,"112,97962509293602",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos

In [48]:
df_preco_corr_tc

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
4,PRECO,2024,12,COMMODITIES_TOTAL_1,"160,28639354962223",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
34,PRECO,2024,11,COMMODITIES_TOTAL_1,"163,57504037220426",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
64,PRECO,2024,10,COMMODITIES_TOTAL_1,"159,66312864186924",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
94,PRECO,2024,9,COMMODITIES_TOTAL_1,"161,85366794116831",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
124,PRECO,2024,8,COMMODITIES_TOTAL_1,"162,25612225919787",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9531,PRECO,1998,5,COMMODITIES_TOTAL_1,"64,98183877034911",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
9555,PRECO,1998,4,COMMODITIES_TOTAL_1,"66,09707804003359",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
9579,PRECO,1998,3,COMMODITIES_TOTAL_1,"68,46266720541971",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
9603,PRECO,1998,2,COMMODITIES_TOTAL_1,"70,81237111129171",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
9627,PRECO,1998,1,COMMODITIES_TOTAL_1,"72,52618931305419",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities

#### Preco - Exp

In [42]:
df_preco_exp_comb, df_preco_exp_mpa, df_preco_exp_mmm, df_preco_exp_ta, df_preco_exp_tc = get_series_by_tipo(df_preco_exp)

In [49]:
df_preco_exp_comb

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
10,PRECO,2024,12,COMMODITIES_CO_GRUPO_4,"124,66928093606960",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
40,PRECO,2024,11,COMMODITIES_CO_GRUPO_4,"142,69278303764270",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
70,PRECO,2024,10,COMMODITIES_CO_GRUPO_4,"139,06335409790276",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
100,PRECO,2024,9,COMMODITIES_CO_GRUPO_4,"148,07315568977367",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
130,PRECO,2024,8,COMMODITIES_CO_GRUPO_4,"148,04082419511724",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
...,...,...,...,...,...,...,...,...,...,...
9220,PRECO,1999,5,COMMODITIES_CO_GRUPO_4,"33,10092583276646",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
9250,PRECO,1999,4,COMMODITIES_CO_GRUPO_4,"43,70078660970057",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
9280,PRECO,1999,3,COMMODITIES_CO_GRUPO_4,"42,74308899401446",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
9310,PRECO,1999,2,COMMODITIES_CO_GRUPO_4,"39,41903920824832",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
9340,PRECO,1999,1,COMMODITIES_CO_GRUPO_4,"21,63977951191331",EXP,USD,Combustíveis,COMMODITIES,Combustíveis

In [50]:
df_preco_exp_mpa

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
11,PRECO,2024,12,COMMODITIES_CO_GRUPO_2,"144,19977605555368",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
41,PRECO,2024,11,COMMODITIES_CO_GRUPO_2,"143,58794362529747",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
71,PRECO,2024,10,COMMODITIES_CO_GRUPO_2,"146,38931566945871",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
101,PRECO,2024,9,COMMODITIES_CO_GRUPO_2,"156,19004409334275",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
131,PRECO,2024,8,COMMODITIES_CO_GRUPO_2,"156,59634901711183",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
...,...,...,...,...,...,...,...,...,...,...
9536,PRECO,1998,5,COMMODITIES_CO_GRUPO_2,"101,07793567069061",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9560,PRECO,1998,4,COMMODITIES_CO_GRUPO_2,"97,24510065795772",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9584,PRECO,1998,3,COMMODITIES_CO_GRUPO_2,"95,95213930774085",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9608,PRECO,1998,2,COMMODITIES_CO_GRUPO_2,"100,55064465093460",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9632,PRECO,1998,1,COMMODITIES_CO_GRUPO_2,"104,37003188387564",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas

In [51]:
df_preco_exp_mmm

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
12,PRECO,2024,12,COMMODITIES_CO_GRUPO_3,"194,31993414767933",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
42,PRECO,2024,11,COMMODITIES_CO_GRUPO_3,"191,52454529283284",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
72,PRECO,2024,10,COMMODITIES_CO_GRUPO_3,"175,45803270744824",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
102,PRECO,2024,9,COMMODITIES_CO_GRUPO_3,"179,38913100477868",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
132,PRECO,2024,8,COMMODITIES_CO_GRUPO_3,"185,95835291053675",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
...,...,...,...,...,...,...,...,...,...,...
9537,PRECO,1998,5,COMMODITIES_CO_GRUPO_3,"57,57251671064958",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9561,PRECO,1998,4,COMMODITIES_CO_GRUPO_3,"57,31906747578356",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9585,PRECO,1998,3,COMMODITIES_CO_GRUPO_3,"57,08211306357689",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9609,PRECO,1998,2,COMMODITIES_CO_GRUPO_3,"56,65336189188282",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9633,PRECO,1998,1,COMMODITIES_CO_GRUPO_3,"57,96917184835647",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"

In [52]:
df_preco_exp_ta

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
13,PRECO,2024,12,COMMODITIES_CO_GRUPO_1,"180,08146229603679",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
43,PRECO,2024,11,COMMODITIES_CO_GRUPO_1,"179,92641620273920",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
73,PRECO,2024,10,COMMODITIES_CO_GRUPO_1,"176,70891311605624",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
103,PRECO,2024,9,COMMODITIES_CO_GRUPO_1,"172,37115156471046",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
133,PRECO,2024,8,COMMODITIES_CO_GRUPO_1,"172,60187148017079",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
...,...,...,...,...,...,...,...,...,...,...
9538,PRECO,1998,5,COMMODITIES_CO_GRUPO_1,"101,43803987191886",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9562,PRECO,1998,4,COMMODITIES_CO_GRUPO_1,"107,72725417226272",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9586,PRECO,1998,3,COMMODITIES_CO_GRUPO_1,"116,43032478716893",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9610,PRECO,1998,2,COMMODITIES_CO_GRUPO_1,"119,71945900899182",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9634,PRECO,1998,1,COMMODITIES_CO_GRUPO_1,"126,08896425079254",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos

In [53]:
df_preco_exp_tc

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
14,PRECO,2024,12,COMMODITIES_TOTAL_1,"169,29384912605829",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
44,PRECO,2024,11,COMMODITIES_TOTAL_1,"172,51191883953987",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
74,PRECO,2024,10,COMMODITIES_TOTAL_1,"167,54637337333094",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
104,PRECO,2024,9,COMMODITIES_TOTAL_1,"169,05154332505464",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
134,PRECO,2024,8,COMMODITIES_TOTAL_1,"169,93434278889939",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9539,PRECO,1998,5,COMMODITIES_TOTAL_1,"81,39140030224694",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9563,PRECO,1998,4,COMMODITIES_TOTAL_1,"84,39984642816944",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9587,PRECO,1998,3,COMMODITIES_TOTAL_1,"88,49085409936008",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9611,PRECO,1998,2,COMMODITIES_TOTAL_1,"90,63914192819091",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9635,PRECO,1998,1,COMMODITIES_TOTAL_1,"94,28163288367739",EXP,USD,Total Commodities,COMMODITIES,Total Commodities

#### Preco - Imp

In [43]:
df_preco_imp_comb, df_preco_imp_mpa, df_preco_imp_mmm, df_preco_imp_ta, df_preco_imp_tc = get_series_by_tipo(df_preco_imp)

In [54]:
df_preco_imp_comb

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
20,PRECO,2024,12,COMMODITIES_CO_GRUPO_4,"125,13048085029550",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
50,PRECO,2024,11,COMMODITIES_CO_GRUPO_4,"131,91945007418656",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
80,PRECO,2024,10,COMMODITIES_CO_GRUPO_4,"127,40845857683627",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
110,PRECO,2024,9,COMMODITIES_CO_GRUPO_4,"132,89200588473466",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
140,PRECO,2024,8,COMMODITIES_CO_GRUPO_4,"137,46135217225120",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
...,...,...,...,...,...,...,...,...,...,...
9230,PRECO,1999,5,COMMODITIES_CO_GRUPO_4,"23,83483702741417",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
9260,PRECO,1999,4,COMMODITIES_CO_GRUPO_4,"20,27867399716541",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
9290,PRECO,1999,3,COMMODITIES_CO_GRUPO_4,"18,63642488792812",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
9320,PRECO,1999,2,COMMODITIES_CO_GRUPO_4,"19,20817020054574",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
9350,PRECO,1999,1,COMMODITIES_CO_GRUPO_4,"17,81627568560446",IMP,USD,Combustíveis,COMMODITIES,Combustíveis

In [55]:
df_preco_imp_mpa

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
21,PRECO,2024,12,COMMODITIES_CO_GRUPO_2,"124,87354338785053",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
51,PRECO,2024,11,COMMODITIES_CO_GRUPO_2,"121,08646647148566",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
81,PRECO,2024,10,COMMODITIES_CO_GRUPO_2,"126,04928959818147",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
111,PRECO,2024,9,COMMODITIES_CO_GRUPO_2,"128,61009664244082",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
141,PRECO,2024,8,COMMODITIES_CO_GRUPO_2,"127,43761012279845",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
...,...,...,...,...,...,...,...,...,...,...
9544,PRECO,1998,5,COMMODITIES_CO_GRUPO_2,"79,94442018982552",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9568,PRECO,1998,4,COMMODITIES_CO_GRUPO_2,"80,49052762685402",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9592,PRECO,1998,3,COMMODITIES_CO_GRUPO_2,"80,32488663399106",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9616,PRECO,1998,2,COMMODITIES_CO_GRUPO_2,"83,78411018264357",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9640,PRECO,1998,1,COMMODITIES_CO_GRUPO_2,"82,90929209676982",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas

In [56]:
df_preco_imp_mmm

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
22,PRECO,2024,12,COMMODITIES_CO_GRUPO_3,"142,11327685811079",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
52,PRECO,2024,11,COMMODITIES_CO_GRUPO_3,"144,08349556673258",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
82,PRECO,2024,10,COMMODITIES_CO_GRUPO_3,"146,73220516317545",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
112,PRECO,2024,9,COMMODITIES_CO_GRUPO_3,"147,41271883699102",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
142,PRECO,2024,8,COMMODITIES_CO_GRUPO_3,"144,36545317747883",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
...,...,...,...,...,...,...,...,...,...,...
9545,PRECO,1998,5,COMMODITIES_CO_GRUPO_3,"48,80166096115625",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9569,PRECO,1998,4,COMMODITIES_CO_GRUPO_3,"49,43239253414087",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9593,PRECO,1998,3,COMMODITIES_CO_GRUPO_3,"52,66463774680933",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9617,PRECO,1998,2,COMMODITIES_CO_GRUPO_3,"50,59900765853483",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9641,PRECO,1998,1,COMMODITIES_CO_GRUPO_3,"50,95613009936341",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"

In [57]:
df_preco_imp_ta

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
23,PRECO,2024,12,COMMODITIES_CO_GRUPO_1,"192,83755319057852",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
53,PRECO,2024,11,COMMODITIES_CO_GRUPO_1,"190,25031025456673",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
83,PRECO,2024,10,COMMODITIES_CO_GRUPO_1,"199,99121446923226",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
113,PRECO,2024,9,COMMODITIES_CO_GRUPO_1,"201,10535737625267",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
143,PRECO,2024,8,COMMODITIES_CO_GRUPO_1,"193,75760041959504",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
...,...,...,...,...,...,...,...,...,...,...
9546,PRECO,1998,5,COMMODITIES_CO_GRUPO_1,"95,47858164584399",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9570,PRECO,1998,4,COMMODITIES_CO_GRUPO_1,"95,01920597184555",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9594,PRECO,1998,3,COMMODITIES_CO_GRUPO_1,"97,84777581655565",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9618,PRECO,1998,2,COMMODITIES_CO_GRUPO_1,"99,08946350509912",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9642,PRECO,1998,1,COMMODITIES_CO_GRUPO_1,"100,17938813467910",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos

In [58]:
df_preco_imp_tc

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
24,PRECO,2024,12,COMMODITIES_TOTAL_1,"138,47335890271017",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
54,PRECO,2024,11,COMMODITIES_TOTAL_1,"142,20057178451918",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
84,PRECO,2024,10,COMMODITIES_TOTAL_1,"141,85917668853392",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
114,PRECO,2024,9,COMMODITIES_TOTAL_1,"144,99731685134262",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
144,PRECO,2024,8,COMMODITIES_TOTAL_1,"145,54196495792226",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9547,PRECO,1998,5,COMMODITIES_TOTAL_1,"38,15514685394161",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
9571,PRECO,1998,4,COMMODITIES_TOTAL_1,"37,16772636429831",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
9595,PRECO,1998,3,COMMODITIES_TOTAL_1,"39,31114875655856",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
9619,PRECO,1998,2,COMMODITIES_TOTAL_1,"40,87159989848013",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
9643,PRECO,1998,1,COMMODITIES_TOTAL_1,"42,64480995344425",IMP,USD,Total Commodities,COMMODITIES,Total Commodities

#### Quantum - Corrente

In [59]:
df_quantum_corr_comb, df_quantum_corr_mpa, df_quantum_corr_mmm, df_quantum_corr_ta, df_quantum_corr_tc = get_series_by_tipo(df_quantum_corr)

In [62]:
df_quantum_corr_comb

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
5,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_4,"170,86239667298014",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
35,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_4,"233,85600690780927",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
65,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_4,"246,02477545029697",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
95,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_4,"212,43019974052945",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
125,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_4,"236,87552439981329",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
...,...,...,...,...,...,...,...,...,...,...
9215,QUANTUM,1999,5,COMMODITIES_CO_GRUPO_4,"78,65842863788147",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
9245,QUANTUM,1999,4,COMMODITIES_CO_GRUPO_4,"61,89108130195891",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
9275,QUANTUM,1999,3,COMMODITIES_CO_GRUPO_4,"84,25723647783289",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
9305,QUANTUM,1999,2,COMMODITIES_CO_GRUPO_4,"35,19023283613130",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis
9335,QUANTUM,1999,1,COMMODITIES_CO_GRUPO_4,"60,46210908575055",CORRENTE,USD,Combustíveis,COMMODITIES,Combustíveis

In [63]:
df_quantum_corr_mpa

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
6,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_2,"228,17373917510147",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
36,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_2,"212,74635450184024",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
66,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_2,"197,01653931072147",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
96,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_2,"181,71751887232529",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
126,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_2,"141,20210060858943",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
...,...,...,...,...,...,...,...,...,...,...
9532,QUANTUM,1998,5,COMMODITIES_CO_GRUPO_2,"47,68898214965516",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9556,QUANTUM,1998,4,COMMODITIES_CO_GRUPO_2,"53,56803297900117",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9580,QUANTUM,1998,3,COMMODITIES_CO_GRUPO_2,"52,79126871518464",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9604,QUANTUM,1998,2,COMMODITIES_CO_GRUPO_2,"44,49775598738645",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9628,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_2,"46,32429504749362",CORRENTE,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas

In [64]:
df_quantum_corr_mmm

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
7,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_3,"150,99963004432325",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
37,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_3,"169,81020648005261",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
67,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_3,"175,55222518426484",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
97,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_3,"175,17917409652583",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
127,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_3,"170,60769491547057",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
...,...,...,...,...,...,...,...,...,...,...
9533,QUANTUM,1998,5,COMMODITIES_CO_GRUPO_3,"52,06248859531956",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9557,QUANTUM,1998,4,COMMODITIES_CO_GRUPO_3,"50,03800229311901",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9581,QUANTUM,1998,3,COMMODITIES_CO_GRUPO_3,"57,26687794801133",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9605,QUANTUM,1998,2,COMMODITIES_CO_GRUPO_3,"47,66220548509861",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9629,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_3,"65,35161591839740",CORRENTE,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"

In [65]:
df_quantum_corr_ta

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
8,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_1,"179,46849171269511",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
38,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_1,"197,89399683825209",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
68,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_1,"238,73056576344166",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
98,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_1,"239,92149304461191",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
128,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_1,"248,44556695669900",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
...,...,...,...,...,...,...,...,...,...,...
9534,QUANTUM,1998,5,COMMODITIES_CO_GRUPO_1,"56,05293356998128",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9558,QUANTUM,1998,4,COMMODITIES_CO_GRUPO_1,"55,13555069968194",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9582,QUANTUM,1998,3,COMMODITIES_CO_GRUPO_1,"38,98561163424998",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9606,QUANTUM,1998,2,COMMODITIES_CO_GRUPO_1,"32,55983921366656",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9630,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_1,"37,05754266327946",CORRENTE,USD,Todos Alimentos,COMMODITIES,Todos Alimentos

In [66]:
df_quantum_corr_tc

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
9,QUANTUM,2024,12,COMMODITIES_TOTAL_1,"173,18432351798012",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
39,QUANTUM,2024,11,COMMODITIES_TOTAL_1,"200,45648503749348",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
69,QUANTUM,2024,10,COMMODITIES_TOTAL_1,"220,42278128620842",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
99,QUANTUM,2024,9,COMMODITIES_TOTAL_1,"211,12596027136038",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
129,QUANTUM,2024,8,COMMODITIES_TOTAL_1,"216,67839248542543",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9535,QUANTUM,1998,5,COMMODITIES_TOTAL_1,"57,87133079643231",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
9559,QUANTUM,1998,4,COMMODITIES_TOTAL_1,"57,85348287251706",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
9583,QUANTUM,1998,3,COMMODITIES_TOTAL_1,"51,15884320719201",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
9607,QUANTUM,1998,2,COMMODITIES_TOTAL_1,"40,78726372101026",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities
9631,QUANTUM,1998,1,COMMODITIES_TOTAL_1,"48,12596859693230",CORRENTE,USD,Total Commodities,COMMODITIES,Total Commodities

#### Quantum - Exp

In [60]:
df_quantum_exp_comb, df_quantum_exp_mpa, df_quantum_exp_mmm, df_quantum_exp_ta, df_quantum_exp_tc = get_series_by_tipo(df_quantum_exp)

In [67]:
df_quantum_exp_comb

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
15,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_4,"245,84601038438771",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
45,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_4,"378,60231126873811",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
75,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_4,"349,68789802972202",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
105,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_4,"274,88801130181952",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
135,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_4,"334,13097925936017",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
...,...,...,...,...,...,...,...,...,...,...
9225,QUANTUM,1999,5,COMMODITIES_CO_GRUPO_4,"2,51945929479649",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
9255,QUANTUM,1999,4,COMMODITIES_CO_GRUPO_4,"1,66203816686671",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
9285,QUANTUM,1999,3,COMMODITIES_CO_GRUPO_4,"1,43881242684452",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
9315,QUANTUM,1999,2,COMMODITIES_CO_GRUPO_4,"2,19737020204176",EXP,USD,Combustíveis,COMMODITIES,Combustíveis
9345,QUANTUM,1999,1,COMMODITIES_CO_GRUPO_4,"14,10583616316809",EXP,USD,Combustíveis,COMMODITIES,Combustíveis

In [68]:
df_quantum_exp_mpa

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
16,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_2,"242,43654780639378",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
46,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_2,"225,41314972320251",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
76,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_2,"206,94204709317668",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
106,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_2,"190,11735086609283",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
136,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_2,"147,71002626697057",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
...,...,...,...,...,...,...,...,...,...,...
9540,QUANTUM,1998,5,COMMODITIES_CO_GRUPO_2,"40,99511225556159",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9564,QUANTUM,1998,4,COMMODITIES_CO_GRUPO_2,"44,38173867309143",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9588,QUANTUM,1998,3,COMMODITIES_CO_GRUPO_2,"42,69403335693000",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9612,QUANTUM,1998,2,COMMODITIES_CO_GRUPO_2,"38,77244977139851",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9636,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_2,"36,70130627941437",EXP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas

In [69]:
df_quantum_exp_mmm

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
17,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_3,"147,81907804930862",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
47,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_3,"159,32179505612561",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
77,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_3,"152,49787564127320",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
107,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_3,"159,77924472597920",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
137,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_3,"147,33218062688869",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
...,...,...,...,...,...,...,...,...,...,...
9541,QUANTUM,1998,5,COMMODITIES_CO_GRUPO_3,"54,20931560461616",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9565,QUANTUM,1998,4,COMMODITIES_CO_GRUPO_3,"54,38193380449833",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9589,QUANTUM,1998,3,COMMODITIES_CO_GRUPO_3,"61,67834090714569",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9613,QUANTUM,1998,2,COMMODITIES_CO_GRUPO_3,"49,77796516349844",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9637,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_3,"73,94792465389726",EXP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"

In [70]:
df_quantum_exp_ta

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
18,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_1,"179,46774036931902",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
48,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_1,"201,48818400774667",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
78,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_1,"244,63343855242030",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
108,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_1,"247,70870794235904",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
138,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_1,"257,31628675167087",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
...,...,...,...,...,...,...,...,...,...,...
9542,QUANTUM,1998,5,COMMODITIES_CO_GRUPO_1,"49,11872667376122",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9566,QUANTUM,1998,4,COMMODITIES_CO_GRUPO_1,"47,93334251810577",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9590,QUANTUM,1998,3,COMMODITIES_CO_GRUPO_1,"27,32489877985990",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9614,QUANTUM,1998,2,COMMODITIES_CO_GRUPO_1,"22,98260143106890",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9638,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_1,"25,10838396845480",EXP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos

In [71]:
df_quantum_exp_tc

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
19,QUANTUM,2024,12,COMMODITIES_TOTAL_1,"185,82852062827286",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
49,QUANTUM,2024,11,COMMODITIES_TOTAL_1,"217,92924436988460",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
79,QUANTUM,2024,10,COMMODITIES_TOTAL_1,"231,21550326664635",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
109,QUANTUM,2024,9,COMMODITIES_TOTAL_1,"221,80655820478185",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
139,QUANTUM,2024,8,COMMODITIES_TOTAL_1,"228,37808144888180",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9543,QUANTUM,1998,5,COMMODITIES_TOTAL_1,"44,40414758411047",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9567,QUANTUM,1998,4,COMMODITIES_TOTAL_1,"43,91502634779285",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9591,QUANTUM,1998,3,COMMODITIES_TOTAL_1,"32,17748864659525",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9615,QUANTUM,1998,2,COMMODITIES_TOTAL_1,"26,86282493448991",EXP,USD,Total Commodities,COMMODITIES,Total Commodities
9639,QUANTUM,1998,1,COMMODITIES_TOTAL_1,"32,07088610388959",EXP,USD,Total Commodities,COMMODITIES,Total Commodities

#### Quantum - Imp

In [61]:
df_quantum_imp_comb, df_quantum_imp_mpa, df_quantum_imp_mmm, df_quantum_imp_ta, df_quantum_imp_tc = get_series_by_tipo(df_quantum_imp)

In [72]:
df_quantum_imp_comb

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
25,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_4,"107,35747872105688",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
55,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_4,"115,97600319366268",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
85,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_4,"159,45151537049497",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
115,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_4,"159,85193690432621",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
145,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_4,"153,68681607650808",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
...,...,...,...,...,...,...,...,...,...,...
9235,QUANTUM,1999,5,COMMODITIES_CO_GRUPO_4,"148,92384251158072",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
9265,QUANTUM,1999,4,COMMODITIES_CO_GRUPO_4,"122,21002817841536",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
9295,QUANTUM,1999,3,COMMODITIES_CO_GRUPO_4,"167,25284712262138",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
9325,QUANTUM,1999,2,COMMODITIES_CO_GRUPO_4,"64,59685107848159",IMP,USD,Combustíveis,COMMODITIES,Combustíveis
9355,QUANTUM,1999,1,COMMODITIES_CO_GRUPO_4,"109,43114777779086",IMP,USD,Combustíveis,COMMODITIES,Combustíveis

In [73]:
df_quantum_imp_mpa

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
26,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_2,"58,62590884552954",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
56,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_2,"60,75148553415427",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
86,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_2,"71,04263232436405",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
116,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_2,"75,81745148985790",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
146,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_2,"62,62792549692258",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
...,...,...,...,...,...,...,...,...,...,...
9548,QUANTUM,1998,5,COMMODITIES_CO_GRUPO_2,"128,06355443636258",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9572,QUANTUM,1998,4,COMMODITIES_CO_GRUPO_2,"161,45239351771474",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9596,QUANTUM,1998,3,COMMODITIES_CO_GRUPO_2,"169,64177766668880",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9620,QUANTUM,1998,2,COMMODITIES_CO_GRUPO_2,"111,89187255582689",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas
9644,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_2,"155,14675915346666",IMP,USD,Matérias-Primas Agrícolas,COMMODITIES,Matérias-Primas Agrícolas

In [74]:
df_quantum_imp_mmm

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
27,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_3,"189,05246277566673",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
57,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_3,"230,86020527738111",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
87,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_3,"278,71599522317507",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
117,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_3,"254,85839664851903",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
147,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_3,"275,64768915266859",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
...,...,...,...,...,...,...,...,...,...,...
9549,QUANTUM,1998,5,COMMODITIES_CO_GRUPO_3,"58,80383823094824",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9573,QUANTUM,1998,4,COMMODITIES_CO_GRUPO_3,"57,05534359761852",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9597,QUANTUM,1998,3,COMMODITIES_CO_GRUPO_3,"58,51749072638817",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9621,QUANTUM,1998,2,COMMODITIES_CO_GRUPO_3,"54,06970675867374",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"
9645,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_3,"58,37790758508214",IMP,USD,"Minerais, Minérios E Metais",COMMODITIES,"Minerais, Minérios e Metais"

In [75]:
df_quantum_imp_ta

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
28,QUANTUM,2024,12,COMMODITIES_CO_GRUPO_1,"162,93325353356767",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
58,QUANTUM,2024,11,COMMODITIES_CO_GRUPO_1,"163,56412518526076",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
88,QUANTUM,2024,10,COMMODITIES_CO_GRUPO_1,"173,89276088876622",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
118,QUANTUM,2024,9,COMMODITIES_CO_GRUPO_1,"161,14925982323538",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
148,QUANTUM,2024,8,COMMODITIES_CO_GRUPO_1,"160,52807249445320",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
...,...,...,...,...,...,...,...,...,...,...
9550,QUANTUM,1998,5,COMMODITIES_CO_GRUPO_1,"127,30738751134739",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9574,QUANTUM,1998,4,COMMODITIES_CO_GRUPO_1,"130,16520093461628",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9598,QUANTUM,1998,3,COMMODITIES_CO_GRUPO_1,"151,93015544230158",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9622,QUANTUM,1998,2,COMMODITIES_CO_GRUPO_1,"127,16868006475084",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos
9646,QUANTUM,1998,1,COMMODITIES_CO_GRUPO_1,"145,25564575150008",IMP,USD,Todos Alimentos,COMMODITIES,Todos Alimentos

In [76]:
df_quantum_imp_tc

,TIPO_INDICE,CO_ANO,CO_MES,CO_COMMODITIES,INDICE,TIPO,TIPO_MOEDA,NO_COMMODITIES,NO_TIPO_CLASSIFICACAO,NO_CLASSIFICACAO_MIN
29,QUANTUM,2024,12,COMMODITIES_TOTAL_1,"135,27295313305990",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
59,QUANTUM,2024,11,COMMODITIES_TOTAL_1,"150,18559809502187",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
89,QUANTUM,2024,10,COMMODITIES_TOTAL_1,"188,51763161970047",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
119,QUANTUM,2024,9,COMMODITIES_TOTAL_1,"180,93315831666555",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
149,QUANTUM,2024,8,COMMODITIES_TOTAL_1,"181,92406372282250",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
...,...,...,...,...,...,...,...,...,...,...
9551,QUANTUM,1998,5,COMMODITIES_TOTAL_1,"117,39770953994946",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
9575,QUANTUM,1998,4,COMMODITIES_TOTAL_1,"122,73751546201296",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
9599,QUANTUM,1998,3,COMMODITIES_TOTAL_1,"137,02309963095269",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
9623,QUANTUM,1998,2,COMMODITIES_TOTAL_1,"104,10339838071651",IMP,USD,Total Commodities,COMMODITIES,Total Commodities
9647,QUANTUM,1998,1,COMMODITIES_TOTAL_1,"115,89236396419047",IMP,USD,Total Commodities,COMMODITIES,Total Commodities